Error - Missing scheme in request url.., see next commit
(scrapyEnv1) PS C:\Users\mvman\projects2\Jobs\Gates_com\gates> scrapy crawl --output out1.csv:csv spider_1
2023-06-11 22:58:27 [scrapy.utils.log] INFO: Scrapy 2.6.1 started (bot: gates)
....
2023-06-11 22:58:28 [scrapy.core.engine] INFO: Spider opened
2023-06-11 22:58:28 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-06-11 22:58:28 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-06-11 22:58:28 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "C:\ProgramFilesVld_x64\anaconda3\envs\scrapyEnv1\lib\site-packages\scrapy\core\engine.py", line 150, in _next_request
    request = next(self.slot.start_requests)
  File "C:\ProgramFilesVld_x64\anaconda3\envs\scrapyEnv1\lib\site-packages\scrapy\spiders\__init__.py", line 64, in start_requests
    yield Request(url, dont_filter=True)
  File "C:\ProgramFilesVld_x64\anaconda3\envs\scrapyEnv1\lib\site-packages\scrapy\http\request\__init__.py", line 60, in __init__
    self._set_url(url)
  File "C:\ProgramFilesVld_x64\anaconda3\envs\scrapyEnv1\lib\site-packages\scrapy\http\request\__init__.py", line 108, in _set_url
    raise ValueError(f'Missing scheme in request url: {self._url}')
ValueError: Missing scheme in request url: c:%5CUsers%5Cmvman%5Cprojects2%5CJobs%5CGates_com%5Ctest1%5Cequipment-clazz=Buses&vehicle-type=School+Buses&year=2017&make=International%2FNavistar&model=CE&engine=Cummins+ISB6.7+Diesel
2023-06-11 22:58:28 [scrapy.core.engine] INFO: Closing spider (finished)
2023-06-11 22:58:28 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
....